"use strict";
exports.__esModule = true;
exports.League = exports.Games = exports.Scores = exports.Players = exports.Teams = void 0;
var teams_1 = require("./teams/");
exports.Teams = teams_1.Teams;
var players_1 = require("./players/");
exports.Players = players_1.Players;
var scores_1 = require("./scores/");
exports.Scores = scores_1.Scores;
var games_1 = require("./games/");
exports.Games = games_1.Games;
var league_1 = require("./league/");
exports.League = league_1.League;
